B_HEADER
 FileSign ASSN FormVers 1.000 CreaSign MATS CreaVers 3.000
 FileMark DBRootFile
E_HEADER

B_DATA 
 B_DBASE halbach 0 BlockSep B_ASNTAB 
  B_ASNTAB halbach 1 BlockSep AssignTo PrvIndex 15216 ParentDB halbach 
   AssignTo object612 12956 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 270 
   AssignTo object611 12940 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 10 
   AssignTo object613 12972 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 170 
   AssignTo object144 13816 
    Material copper 4 
   AssignTo object190 13954 
    Material copper 4 
   AssignTo object185 13939 
    Material copper 4 
   AssignTo object149 13831 
    Material copper 4 
   AssignTo object182 13930 
    Material copper 4 
   AssignTo object152 13840 
    Material copper 4 
   AssignTo object179 13921 
    Material copper 4 
   AssignTo object155 13849 
    Material copper 4 
   AssignTo object176 13912 
    Material copper 4 
   AssignTo object158 13858 
    Material copper 4 
   AssignTo object173 13903 
    Material copper 4 
   AssignTo object161 13867 
    Material copper 4 
   AssignTo object170 13894 
    Material copper 4 
   AssignTo object164 13876 
    Material copper 4 
   AssignTo object146 13822 
    Material copper 4 
   AssignTo object167 13885 
    Material copper 4 
   AssignTo object145 13819 
    Material copper 4 
   AssignTo object189 13951 
    Material copper 4 
   AssignTo object186 13942 
    Material copper 4 
   AssignTo object148 13828 
    Material copper 4 
   AssignTo object183 13933 
    Material copper 4 
   AssignTo object151 13837 
    Material copper 4 
   AssignTo object180 13924 
    Material copper 4 
   AssignTo object154 13846 
    Material copper 4 
   AssignTo object610 12924 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 110 
   AssignTo object614 12988 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 70 
   AssignTo object177 13915 
    Material copper 4 
   AssignTo object157 13855 
    Material copper 4 
   AssignTo object174 13906 
    Material copper 4 
   AssignTo object160 13864 
    Material copper 4 
   AssignTo object171 13897 
    Material copper 4 
   AssignTo object163 13873 
    Material copper 4 
   AssignTo object168 13888 
    Material copper 4 
   AssignTo object166 13882 
    Material copper 4 
   AssignTo object188 13948 
    Material copper 4 
   AssignTo object143 13813 
    Material copper 4 
   AssignTo object187 13945 
    Material copper 4 
   AssignTo object147 13825 
    Material copper 4 
   AssignTo object184 13936 
    Material copper 4 
   AssignTo object150 13834 
    Material copper 4 
   AssignTo object181 13927 
    Material copper 4 
   AssignTo object153 13843 
    Material copper 4 
   AssignTo object178 13918 
    Material copper 4 
   AssignTo object156 13852 
    Material copper 4 
   AssignTo object175 13909 
    Material copper 4 
   AssignTo object159 13861 
    Material copper 4 
   AssignTo object172 13900 
    Material copper 4 
   AssignTo object162 13870 
    Material copper 4 
   AssignTo object169 13891 
    Material copper 4 
   AssignTo object165 13879 
    Material copper 4 
   AssignTo object119 13741 
    Material copper 4 
   AssignTo object196 13972 
    Material copper 4 
   AssignTo object116 13732 
    Material copper 4 
   AssignTo object220 14044 
    Material copper 4 
   AssignTo object113 13723 
    Material copper 4 
   AssignTo object223 14053 
    Material copper 4 
   AssignTo object118 13738 
    Material copper 4 
   AssignTo object218 14038 
    Material copper 4 
   AssignTo object115 13729 
    Material copper 4 
   AssignTo object221 14047 
    Material copper 4 
   AssignTo object110 13714 
    Material copper 4 
   AssignTo object226 14062 
    Material copper 4 
   AssignTo object112 13720 
    Material copper 4 
   AssignTo object224 14056 
    Material copper 4 
   AssignTo object117 13735 
    Material copper 4 
   AssignTo object219 14041 
    Material copper 4 
   AssignTo object107 13705 
    Material copper 4 
   AssignTo object229 14071 
    Material copper 4 
   AssignTo object114 13726 
    Material copper 4 
   AssignTo object222 14050 
    Material copper 4 
   AssignTo object109 13711 
    Material copper 4 
   AssignTo object227 14065 
    Material copper 4 
   AssignTo object104 13696 
    Material copper 4 
   AssignTo object232 14080 
    Material copper 4 
   AssignTo object609 12908 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 210 
   AssignTo object615 13004 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 330 
   AssignTo object111 13717 
    Material copper 4 
   AssignTo object225 14059 
    Material copper 4 
   AssignTo object106 13702 
    Material copper 4 
   AssignTo object230 14074 
    Material copper 4 
   AssignTo object101 13687 
    Material copper 4 
   AssignTo object235 14089 
    Material copper 4 
   AssignTo object108 13708 
    Material copper 4 
   AssignTo object228 14068 
    Material copper 4 
   AssignTo object103 13693 
    Material copper 4 
   AssignTo object233 14083 
    Material copper 4 
   AssignTo object142 13810 
    Material copper 4 
   AssignTo object192 13960 
    Material copper 4 
   AssignTo object105 13699 
    Material copper 4 
   AssignTo object231 14077 
    Material copper 4 
   AssignTo object100 13684 
    Material copper 4 
   AssignTo object236 14092 
    Material copper 4 
   AssignTo object102 13690 
    Material copper 4 
   AssignTo object234 14086 
    Material copper 4 
   AssignTo object96 13672 
    Material copper 4 
   AssignTo object240 14104 
    Material copper 4 
   AssignTo object141 13807 
    Material copper 4 
   AssignTo object195 13969 
    Material copper 4 
   AssignTo object99 13681 
    Material copper 4 
   AssignTo object237 14095 
    Material copper 4 
   AssignTo object137 13795 
    Material copper 4 
   AssignTo object199 13981 
    Material copper 4 
   AssignTo object97 13675 
    Material copper 4 
   AssignTo object239 14101 
    Material copper 4 
   AssignTo object95 13669 
    Material copper 4 
   AssignTo object238 14098 
    Material copper 4 
   AssignTo object134 13786 
    Material copper 4 
   AssignTo object202 13990 
    Material copper 4 
   AssignTo object138 13798 
    Material copper 4 
   AssignTo object198 13978 
    Material copper 4 
   AssignTo object140 13804 
    Material copper 4 
   AssignTo object191 13957 
    Material copper 4 
   AssignTo object131 13777 
    Material copper 4 
   AssignTo object205 13999 
    Material copper 4 
   AssignTo object135 13789 
    Material copper 4 
   AssignTo object201 13987 
    Material copper 4 
   AssignTo object139 13801 
    Material copper 4 
   AssignTo object197 13975 
    Material copper 4 
   AssignTo object128 13768 
    Material copper 4 
   AssignTo object208 14008 
    Material copper 4 
   AssignTo object132 13780 
    Material copper 4 
   AssignTo object204 13996 
    Material copper 4 
   AssignTo object136 13792 
    Material copper 4 
   AssignTo object200 13984 
    Material copper 4 
   AssignTo object593 15192 
    Material air 2 
   AssignTo object594 15195 
    Material air 2 
   AssignTo object125 13759 
    Material copper 4 
   AssignTo object211 14017 
    Material copper 4 
   AssignTo object129 13771 
    Material copper 4 
   AssignTo object207 14005 
    Material copper 4 
   AssignTo object133 13783 
    Material copper 4 
   AssignTo object203 13993 
    Material copper 4 
   AssignTo object122 13750 
    Material copper 4 
   AssignTo object214 14026 
    Material copper 4 
   AssignTo object126 13762 
    Material copper 4 
   AssignTo object210 14014 
    Material copper 4 
   AssignTo object130 13774 
    Material copper 4 
   AssignTo object206 14002 
    Material copper 4 
   AssignTo object608 12892 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 310 
   AssignTo object616 13020 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 230 
   AssignTo object98 13678 
    Material copper 4 
   AssignTo object217 14035 
    Material copper 4 
   AssignTo object123 13753 
    Material copper 4 
   AssignTo object213 14023 
    Material copper 4 
   AssignTo object127 13765 
    Material copper 4 
   AssignTo object209 14011 
    Material copper 4 
   AssignTo object120 13744 
    Material copper 4 
   AssignTo object216 14032 
    Material copper 4 
   AssignTo object124 13756 
    Material copper 4 
   AssignTo object212 14020 
    Material copper 4 
   AssignTo object121 13747 
    Material copper 4 
   AssignTo object215 14029 
    Material copper 4 
   AssignTo object607 12876 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 50 
   AssignTo object617 13036 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 130 
   AssignTo object71 13597 
    Material copper 4 
   AssignTo object244 14116 
    Material copper 4 
   AssignTo object70 13594 
    Material copper 4 
   AssignTo object266 14182 
    Material copper 4 
   AssignTo object68 13588 
    Material copper 4 
   AssignTo object268 14188 
    Material copper 4 
   AssignTo object69 13591 
    Material copper 4 
   AssignTo object267 14185 
    Material copper 4 
   AssignTo object67 13585 
    Material copper 4 
   AssignTo object269 14191 
    Material copper 4 
   AssignTo object65 13579 
    Material copper 4 
   AssignTo object271 14197 
    Material copper 4 
   AssignTo object66 13582 
    Material copper 4 
   AssignTo object270 14194 
    Material copper 4 
   AssignTo object64 13576 
    Material copper 4 
   AssignTo object272 14200 
    Material copper 4 
   AssignTo object592 15189 
    Material air 2 
   AssignTo object595 15198 
    Material air 2 
   AssignTo object62 13570 
    Material copper 4 
   AssignTo object274 14206 
    Material copper 4 
   AssignTo object63 13573 
    Material copper 4 
   AssignTo object273 14203 
    Material copper 4 
   AssignTo object61 13567 
    Material copper 4 
   AssignTo object275 14209 
    Material copper 4 
   AssignTo object59 13561 
    Material copper 4 
   AssignTo object277 14215 
    Material copper 4 
   AssignTo object60 13564 
    Material copper 4 
   AssignTo object276 14212 
    Material copper 4 
   AssignTo object58 13558 
    Material copper 4 
   AssignTo object278 14218 
    Material copper 4 
   AssignTo object56 13552 
    Material copper 4 
   AssignTo object280 14224 
    Material copper 4 
   AssignTo object57 13555 
    Material copper 4 
   AssignTo object279 14221 
    Material copper 4 
   AssignTo object55 13549 
    Material copper 4 
   AssignTo object281 14227 
    Material copper 4 
   AssignTo object53 13543 
    Material copper 4 
   AssignTo object283 14233 
    Material copper 4 
   AssignTo object54 13546 
    Material copper 4 
   AssignTo object282 14230 
    Material copper 4 
   AssignTo object581 15156 
    Material air 2 
   AssignTo object582 15159 
    Material air 2 
   AssignTo object52 13540 
    Material copper 4 
   AssignTo object284 14236 
    Material copper 4 
   AssignTo object51 13537 
    Material copper 4 
   AssignTo object285 14239 
    Material copper 4 
   AssignTo object94 13666 
    Material copper 4 
   AssignTo object242 14110 
    Material copper 4 
   AssignTo object93 13663 
    Material copper 4 
   AssignTo object243 14113 
    Material copper 4 
   AssignTo object47 13525 
    Material copper 4 
    OrientAt 0 0 0 
   AssignTo object286 14242 
    Material copper 4 
   AssignTo object48 13528 
    Material copper 4 
   AssignTo object288 14248 
    Material copper 4 
   AssignTo object49 13531 
    Material copper 4 
   AssignTo object287 14245 
    Material copper 4 
   AssignTo object606 12860 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 150 
   AssignTo object618 13052 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 30 
   AssignTo object92 13660 
    Material copper 4 
   AssignTo object241 14107 
    Material copper 4 
   AssignTo object89 13651 
    Material copper 4 
   AssignTo object247 14125 
    Material copper 4 
   AssignTo object90 13654 
    Material copper 4 
   AssignTo object246 14122 
    Material copper 4 
   AssignTo object91 13657 
    Material copper 4 
   AssignTo object245 14119 
    Material copper 4 
   AssignTo object86 13642 
    Material copper 4 
   AssignTo object250 14134 
    Material copper 4 
   AssignTo object87 13645 
    Material copper 4 
   AssignTo object249 14131 
    Material copper 4 
   AssignTo object88 13648 
    Material copper 4 
   AssignTo object248 14128 
    Material copper 4 
   AssignTo object83 13633 
    Material copper 4 
   AssignTo object253 14143 
    Material copper 4 
   AssignTo object84 13636 
    Material copper 4 
   AssignTo object252 14140 
    Material copper 4 
   AssignTo object85 13639 
    Material copper 4 
   AssignTo object251 14137 
    Material copper 4 
   AssignTo object80 13624 
    Material copper 4 
   AssignTo object256 14152 
    Material copper 4 
   AssignTo object81 13627 
    Material copper 4 
   AssignTo object255 14149 
    Material copper 4 
   AssignTo object82 13630 
    Material copper 4 
   AssignTo object254 14146 
    Material copper 4 
   AssignTo object77 13615 
    Material copper 4 
   AssignTo object259 14161 
    Material copper 4 
   AssignTo object78 13618 
    Material copper 4 
   AssignTo object258 14158 
    Material copper 4 
   AssignTo object79 13621 
    Material copper 4 
   AssignTo object257 14155 
    Material copper 4 
   AssignTo object74 13606 
    Material copper 4 
   AssignTo object262 14170 
    Material copper 4 
   AssignTo object580 15153 
    Material air 2 
   AssignTo object583 15162 
    Material air 2 
   AssignTo object75 13609 
    Material copper 4 
   AssignTo object261 14167 
    Material copper 4 
   AssignTo object76 13612 
    Material copper 4 
   AssignTo object260 14164 
    Material copper 4 
   AssignTo object50 13534 
    Material copper 4 
   AssignTo object265 14179 
    Material copper 4 
   AssignTo object72 13600 
    Material copper 4 
   AssignTo object264 14176 
    Material copper 4 
   AssignTo object73 13603 
    Material copper 4 
   AssignTo object263 14173 
    Material copper 4 
   AssignTo object605 12844 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 250 
   AssignTo object619 13068 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 290 
   AssignTo object591 15186 
    Material air 2 
   AssignTo object596 15201 
    Material air 2 
   AssignTo object25 13459 
    Material copper 4 
   AssignTo object292 14260 
    Material copper 4 
   AssignTo object24 13456 
    Material copper 4 
   AssignTo object314 14326 
    Material copper 4 
   AssignTo object23 13453 
    Material copper 4 
   AssignTo object315 14329 
    Material copper 4 
   AssignTo object22 13450 
    Material copper 4 
   AssignTo object316 14332 
    Material copper 4 
   AssignTo object21 13447 
    Material copper 4 
   AssignTo object317 14335 
    Material copper 4 
   AssignTo object20 13444 
    Material copper 4 
   AssignTo object318 14338 
    Material copper 4 
   AssignTo object620 13084 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 190 
   AssignTo object604 12828 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 350 
   AssignTo object19 13441 
    Material copper 4 
   AssignTo object319 14341 
    Material copper 4 
   AssignTo object18 13438 
    Material copper 4 
   AssignTo object320 14344 
    Material copper 4 
   AssignTo object17 13435 
    Material copper 4 
   AssignTo object321 14347 
    Material copper 4 
   AssignTo object16 13432 
    Material copper 4 
   AssignTo object322 14350 
    Material copper 4 
   AssignTo object579 15150 
    Material air 2 
   AssignTo object584 15165 
    Material air 2 
   AssignTo object15 13429 
    Material copper 4 
   AssignTo object323 14353 
    Material copper 4 
   AssignTo object14 13426 
    Material copper 4 
   AssignTo object324 14356 
    Material copper 4 
   AssignTo object13 13423 
    Material copper 4 
   AssignTo object325 14359 
    Material copper 4 
   AssignTo object12 13420 
    Material copper 4 
   AssignTo object326 14362 
    Material copper 4 
   AssignTo object11 13417 
    Material copper 4 
   AssignTo object327 14365 
    Material copper 4 
   AssignTo object10 13414 
    Material copper 4 
   AssignTo object328 14368 
    Material copper 4 
   AssignTo object9 13411 
    Material copper 4 
   AssignTo object329 14371 
    Material copper 4 
   AssignTo object8 13408 
    Material copper 4 
   AssignTo object330 14374 
    Material copper 4 
   AssignTo object7 13405 
    Material copper 4 
   AssignTo object331 14377 
    Material copper 4 
   AssignTo object6 13402 
    Material copper 4 
   AssignTo object332 14380 
    Material copper 4 
   AssignTo object5 13399 
    Material copper 4 
   AssignTo object333 14383 
    Material copper 4 
   AssignTo object194 13966 
    Material copper 4 
   AssignTo object290 14254 
    Material copper 4 
   AssignTo object193 13963 
    Material copper 4 
   AssignTo object291 14257 
    Material copper 4 
   AssignTo object1 13387 
    Material copper 4 
   AssignTo object334 14386 
    Material copper 4 
   AssignTo object46 13522 
    Material copper 4 
   AssignTo object289 14251 
    Material copper 4 
   AssignTo object3 13393 
    Material copper 4 
   AssignTo object335 14389 
    Material copper 4 
   AssignTo object2 13390 
    Material copper 4 
   AssignTo object336 14392 
    Material copper 4 
   AssignTo object45 13519 
    Material copper 4 
   AssignTo object293 14263 
    Material copper 4 
   AssignTo object44 13516 
    Material copper 4 
   AssignTo object294 14266 
    Material copper 4 
   AssignTo object43 13513 
    Material copper 4 
   AssignTo object295 14269 
    Material copper 4 
   AssignTo object42 13510 
    Material copper 4 
   AssignTo object296 14272 
    Material copper 4 
   AssignTo object41 13507 
    Material copper 4 
   AssignTo object297 14275 
    Material copper 4 
   AssignTo object40 13504 
    Material copper 4 
   AssignTo object298 14278 
    Material copper 4 
   AssignTo object603 12812 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 90 
   AssignTo object621 13100 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 90 
   AssignTo object39 13501 
    Material copper 4 
   AssignTo object299 14281 
    Material copper 4 
   AssignTo object38 13498 
    Material copper 4 
   AssignTo object300 14284 
    Material copper 4 
   AssignTo object37 13495 
    Material copper 4 
   AssignTo object301 14287 
    Material copper 4 
   AssignTo object36 13492 
    Material copper 4 
   AssignTo object302 14290 
    Material copper 4 
   AssignTo object35 13489 
    Material copper 4 
   AssignTo object303 14293 
    Material copper 4 
   AssignTo object34 13486 
    Material copper 4 
   AssignTo object304 14296 
    Material copper 4 
   AssignTo object33 13483 
    Material copper 4 
   AssignTo object305 14299 
    Material copper 4 
   AssignTo object32 13480 
    Material copper 4 
   AssignTo object306 14302 
    Material copper 4 
   AssignTo object31 13477 
    Material copper 4 
   AssignTo object307 14305 
    Material copper 4 
   AssignTo object30 13474 
    Material copper 4 
   AssignTo object308 14308 
    Material copper 4 
   AssignTo object29 13471 
    Material copper 4 
   AssignTo object309 14311 
    Material copper 4 
   AssignTo object28 13468 
    Material copper 4 
   AssignTo object310 14314 
    Material copper 4 
   AssignTo object27 13465 
    Material copper 4 
   AssignTo object311 14317 
    Material copper 4 
   AssignTo object26 13462 
    Material copper 4 
   AssignTo object312 14320 
    Material copper 4 
   AssignTo object4 13396 
    Material copper 4 
   AssignTo object313 14323 
    Material copper 4 
   AssignTo object578 15147 
    Material air 2 
   AssignTo object585 15168 
    Material air 2 
   AssignTo object590 15183 
    Material air 2 
   AssignTo object597 15204 
    Material air 2 
   AssignTo object577 15120 
    Material air 2 
   AssignTo object622 13116 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 350 
   AssignTo object638 13372 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 190 
   AssignTo object551 15037 
    Material copper 4 
   AssignTo object363 14473 
    Material copper 4 
   AssignTo object552 15040 
    Material copper 4 
   AssignTo object362 14470 
    Material copper 4 
   AssignTo object553 15043 
    Material copper 4 
   AssignTo object340 14404 
    Material copper 4 
   AssignTo object548 15028 
    Material copper 4 
   AssignTo object366 14482 
    Material copper 4 
   AssignTo object549 15031 
    Material copper 4 
   AssignTo object365 14479 
    Material copper 4 
   AssignTo object550 15034 
    Material copper 4 
   AssignTo object364 14476 
    Material copper 4 
   AssignTo object545 15019 
    Material copper 4 
   AssignTo object369 14491 
    Material copper 4 
   AssignTo object546 15022 
    Material copper 4 
   AssignTo object368 14488 
    Material copper 4 
   AssignTo object547 15025 
    Material copper 4 
   AssignTo object367 14485 
    Material copper 4 
   AssignTo object542 15010 
    Material copper 4 
   AssignTo object372 14500 
    Material copper 4 
   AssignTo object543 15013 
    Material copper 4 
   AssignTo object371 14497 
    Material copper 4 
   AssignTo object544 15016 
    Material copper 4 
   AssignTo object370 14494 
    Material copper 4 
   AssignTo object539 15001 
    Material copper 4 
   AssignTo object375 14509 
    Material copper 4 
   AssignTo object540 15004 
    Material copper 4 
   AssignTo object374 14506 
    Material copper 4 
   AssignTo object541 15007 
    Material copper 4 
   AssignTo object373 14503 
    Material copper 4 
   AssignTo object536 14992 
    Material copper 4 
   AssignTo object378 14518 
    Material copper 4 
   AssignTo object537 14995 
    Material copper 4 
   AssignTo object377 14515 
    Material copper 4 
   AssignTo object538 14998 
    Material copper 4 
   AssignTo object376 14512 
    Material copper 4 
   AssignTo object533 14983 
    Material copper 4 
   AssignTo object381 14527 
    Material copper 4 
   AssignTo object637 13356 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 290 
   AssignTo object623 13132 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 250 
   AssignTo object534 14986 
    Material copper 4 
   AssignTo object380 14524 
    Material copper 4 
   AssignTo object535 14989 
    Material copper 4 
   AssignTo object379 14521 
    Material copper 4 
   AssignTo object529 14971 
    Material copper 4 
   AssignTo object382 14530 
    Material copper 4 
   AssignTo object589 15180 
    Material air 2 
   AssignTo object586 15171 
    Material air 2 
   AssignTo object575 15109 
    Material copper 4 
   AssignTo object339 14401 
    Material copper 4 
   AssignTo object576 15112 
    Material copper 4 
   AssignTo object338 14398 
    Material copper 4 
   AssignTo object574 15106 
    Material copper 4 
   AssignTo object337 14395 
    Material copper 4 
   AssignTo object531 14977 
    Material copper 4 
   AssignTo object383 14533 
    Material copper 4 
   AssignTo object530 14974 
    Material copper 4 
   AssignTo object384 14536 
    Material copper 4 
   AssignTo object573 15103 
    Material copper 4 
   AssignTo object341 14407 
    Material copper 4 
   AssignTo object572 15100 
    Material copper 4 
   AssignTo object342 14410 
    Material copper 4 
   AssignTo object570 15094 
    Material copper 4 
   AssignTo object344 14416 
    Material copper 4 
   AssignTo object571 15097 
    Material copper 4 
   AssignTo object343 14413 
    Material copper 4 
   AssignTo object569 15091 
    Material copper 4 
   AssignTo object345 14419 
    Material copper 4 
   AssignTo object567 15085 
    Material copper 4 
   AssignTo object347 14425 
    Material copper 4 
   AssignTo object568 15088 
    Material copper 4 
   AssignTo object346 14422 
    Material copper 4 
   AssignTo object566 15082 
    Material copper 4 
   AssignTo object348 14428 
    Material copper 4 
   AssignTo object564 15076 
    Material copper 4 
   AssignTo object350 14434 
    Material copper 4 
   AssignTo object565 15079 
    Material copper 4 
   AssignTo object349 14431 
    Material copper 4 
   AssignTo object563 15073 
    Material copper 4 
   AssignTo object351 14437 
    Material copper 4 
   AssignTo object561 15067 
    Material copper 4 
   AssignTo object353 14443 
    Material copper 4 
   AssignTo object562 15070 
    Material copper 4 
   AssignTo object352 14440 
    Material copper 4 
   AssignTo object560 15064 
    Material copper 4 
   AssignTo object354 14446 
    Material copper 4 
   AssignTo object558 15058 
    Material copper 4 
   AssignTo object356 14452 
    Material copper 4 
   AssignTo object559 15061 
    Material copper 4 
   AssignTo object355 14449 
    Material copper 4 
   AssignTo object557 15055 
    Material copper 4 
   AssignTo object357 14455 
    Material copper 4 
   AssignTo object555 15049 
    Material copper 4 
   AssignTo object359 14461 
    Material copper 4 
   AssignTo object601 15216 
    Material air 2 
   AssignTo object598 15207 
    Material air 2 
   AssignTo object556 15052 
    Material copper 4 
   AssignTo object358 14458 
    Material copper 4 
   AssignTo object554 15046 
    Material copper 4 
   AssignTo object360 14464 
    Material copper 4 
   AssignTo object532 14980 
    Material copper 4 
   AssignTo object361 14467 
    Material copper 4 
   AssignTo object588 15177 
    Material air 2 
   AssignTo object587 15174 
    Material air 2 
   AssignTo object636 13340 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 30 
   AssignTo object624 13148 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 150 
   AssignTo object503 14893 
    Material copper 4 
   AssignTo object411 14617 
    Material copper 4 
   AssignTo object500 14884 
    Material copper 4 
   AssignTo object414 14626 
    Material copper 4 
   AssignTo object504 14896 
    Material copper 4 
   AssignTo object410 14614 
    Material copper 4 
   AssignTo object497 14875 
    Material copper 4 
   AssignTo object417 14635 
    Material copper 4 
   AssignTo object501 14887 
    Material copper 4 
   AssignTo object413 14623 
    Material copper 4 
   AssignTo object505 14899 
    Material copper 4 
   AssignTo object388 14548 
    Material copper 4 
   AssignTo object494 14866 
    Material copper 4 
   AssignTo object420 14644 
    Material copper 4 
   AssignTo object498 14878 
    Material copper 4 
   AssignTo object416 14632 
    Material copper 4 
   AssignTo object502 14890 
    Material copper 4 
   AssignTo object412 14620 
    Material copper 4 
   AssignTo object491 14857 
    Material copper 4 
   AssignTo object423 14653 
    Material copper 4 
   AssignTo object495 14869 
    Material copper 4 
   AssignTo object419 14641 
    Material copper 4 
   AssignTo object499 14881 
    Material copper 4 
   AssignTo object415 14629 
    Material copper 4 
   AssignTo object635 13324 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 130 
   AssignTo object625 13164 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 50 
   AssignTo object488 14848 
    Material copper 4 
   AssignTo object426 14662 
    Material copper 4 
   AssignTo object492 14860 
    Material copper 4 
   AssignTo object422 14650 
    Material copper 4 
   AssignTo object496 14872 
    Material copper 4 
   AssignTo object418 14638 
    Material copper 4 
   AssignTo object485 14839 
    Material copper 4 
   AssignTo object429 14671 
    Material copper 4 
   AssignTo object489 14851 
    Material copper 4 
   AssignTo object425 14659 
    Material copper 4 
   AssignTo object493 14863 
    Material copper 4 
   AssignTo object421 14647 
    Material copper 4 
   AssignTo object481 14827 
    Material copper 4 
   AssignTo object430 14674 
    Material copper 4 
   AssignTo object486 14842 
    Material copper 4 
   AssignTo object428 14668 
    Material copper 4 
   AssignTo object600 15213 
    Material air 2 
   AssignTo object599 15210 
    Material air 2 
   AssignTo object490 14854 
    Material copper 4 
   AssignTo object424 14656 
    Material copper 4 
   AssignTo object526 14962 
    Material copper 4 
   AssignTo object385 14539 
    Material copper 4 
   AssignTo object527 14965 
    Material copper 4 
   AssignTo object387 14545 
    Material copper 4 
   AssignTo object487 14845 
    Material copper 4 
   AssignTo object427 14665 
    Material copper 4 
   AssignTo object525 14959 
    Material copper 4 
   AssignTo object389 14551 
    Material copper 4 
   AssignTo object483 14833 
    Material copper 4 
   AssignTo object431 14677 
    Material copper 4 
   AssignTo object528 14968 
    Material copper 4 
   AssignTo object386 14542 
    Material copper 4 
   AssignTo object522 14950 
    Material copper 4 
   AssignTo object392 14560 
    Material copper 4 
   AssignTo object524 14956 
    Material copper 4 
   AssignTo object390 14554 
    Material copper 4 
   AssignTo object519 14941 
    Material copper 4 
   AssignTo object395 14569 
    Material copper 4 
   AssignTo object482 14830 
    Material copper 4 
   AssignTo object432 14680 
    Material copper 4 
   AssignTo object521 14947 
    Material copper 4 
   AssignTo object393 14563 
    Material copper 4 
   AssignTo object516 14932 
    Material copper 4 
   AssignTo object398 14578 
    Material copper 4 
   AssignTo object523 14953 
    Material copper 4 
   AssignTo object391 14557 
    Material copper 4 
   AssignTo object518 14938 
    Material copper 4 
   AssignTo object396 14572 
    Material copper 4 
   AssignTo object513 14923 
    Material copper 4 
   AssignTo object401 14587 
    Material copper 4 
   AssignTo object520 14944 
    Material copper 4 
   AssignTo object394 14566 
    Material copper 4 
   AssignTo object515 14929 
    Material copper 4 
   AssignTo object399 14581 
    Material copper 4 
   AssignTo object510 14914 
    Material copper 4 
   AssignTo object404 14596 
    Material copper 4 
   AssignTo object517 14935 
    Material copper 4 
   AssignTo object397 14575 
    Material copper 4 
   AssignTo object507 14905 
    Material copper 4 
   AssignTo object407 14605 
    Material copper 4 
   AssignTo object512 14920 
    Material copper 4 
   AssignTo object402 14590 
    Material copper 4 
   AssignTo object514 14926 
    Material copper 4 
   AssignTo object400 14584 
    Material copper 4 
   AssignTo object509 14911 
    Material copper 4 
   AssignTo object405 14599 
    Material copper 4 
   AssignTo object506 14902 
    Material copper 4 
   AssignTo object408 14608 
    Material copper 4 
   AssignTo object511 14917 
    Material copper 4 
   AssignTo object403 14593 
    Material copper 4 
   AssignTo object508 14908 
    Material copper 4 
   AssignTo object406 14602 
    Material copper 4 
   AssignTo object484 14836 
    Material copper 4 
   AssignTo object409 14611 
    Material copper 4 
   AssignTo object634 13308 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 230 
   AssignTo object626 13180 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 310 
   AssignTo object455 14749 
    Material copper 4 
   AssignTo object459 14761 
    Material copper 4 
   AssignTo object452 14740 
    Material copper 4 
   AssignTo object462 14770 
    Material copper 4 
   AssignTo object449 14731 
    Material copper 4 
   AssignTo object465 14779 
    Material copper 4 
   AssignTo object446 14722 
    Material copper 4 
   AssignTo object468 14788 
    Material copper 4 
   AssignTo object443 14713 
    Material copper 4 
   AssignTo object471 14797 
    Material copper 4 
   AssignTo object440 14704 
    Material copper 4 
   AssignTo object474 14806 
    Material copper 4 
   AssignTo object437 14695 
    Material copper 4 
   AssignTo object477 14815 
    Material copper 4 
   AssignTo object433 14683 
    Material copper 4 
   AssignTo object478 14818 
    Material copper 4 
   AssignTo object456 14752 
    Material copper 4 
   AssignTo object458 14758 
    Material copper 4 
   AssignTo object453 14743 
    Material copper 4 
   AssignTo object461 14767 
    Material copper 4 
   AssignTo object450 14734 
    Material copper 4 
   AssignTo object464 14776 
    Material copper 4 
   AssignTo object447 14725 
    Material copper 4 
   AssignTo object467 14785 
    Material copper 4 
   AssignTo object444 14716 
    Material copper 4 
   AssignTo object470 14794 
    Material copper 4 
   AssignTo object441 14707 
    Material copper 4 
   AssignTo object473 14803 
    Material copper 4 
   AssignTo object438 14698 
    Material copper 4 
   AssignTo object476 14812 
    Material copper 4 
   AssignTo object479 14821 
    Material copper 4 
   AssignTo object435 14689 
    Material copper 4 
   AssignTo object457 14755 
    Material copper 4 
   AssignTo object436 14692 
    Material copper 4 
   AssignTo object602 12808 
    Material polyethylene 63 
   AssignTo object454 14746 
    Material copper 4 
   AssignTo object460 14764 
    Material copper 4 
   AssignTo object451 14737 
    Material copper 4 
   AssignTo object463 14773 
    Material copper 4 
   AssignTo object448 14728 
    Material copper 4 
   AssignTo object466 14782 
    Material copper 4 
   AssignTo object445 14719 
    Material copper 4 
   AssignTo object469 14791 
    Material copper 4 
   AssignTo object442 14710 
    Material copper 4 
   AssignTo object472 14800 
    Material copper 4 
   AssignTo object439 14701 
    Material copper 4 
   AssignTo object475 14809 
    Material copper 4 
   AssignTo object480 14824 
    Material copper 4 
   AssignTo object434 14686 
    Material copper 4 
   AssignTo object633 13292 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 330 
   AssignTo object627 13196 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 210 
   AssignTo object632 13276 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 70 
   AssignTo object628 13212 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 110 
   AssignTo object631 13260 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 170 
   AssignTo object629 13228 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 10 
   AssignTo object630 13244 
    Material NdFe35 53 
    OrientAbsolute OrientAt 0 0 270 
   AssignTo background 0 
    Material air 2 
  E_ASNTAB 
 E_DBASE 
E_DATA 
